import 'package:progit_activity_booker/models/activity.dart';

Map<String, Activity> ACTIVITIES = {
  '1': Activity(
    uid: '1',
    createdById: '5',
    title: 'Spille padel',
    location: 'Nordic padel',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 5,
    description: 'Bli med å spille',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 3,
  ),
  '2': Activity(
    uid: '2',
    createdById: '14',
    title: 'Flyvning hos Modern Activity Center',
    location: 'Modern Activity Center',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description:
        'Vi skal fly i vindtunnel. Lang beskrivelse  Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 14,
  ),
  '3': Activity(
    uid: '3',
    createdById: '15',
    title: 'Fadag',
    location: 'Ukjent',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description: 'Vi skal ha kurs i flutter.',
    category: ACTIVITY_CATEGORY.SOCIAL,
    numberOfSignUps: 18,
  ),
  '4': Activity(
    uid: '4',
    createdById: '5',
    title: 'Spille padel',
    location: 'Nordic padel',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 5,
    description: 'Bli med å spille',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 3,
  ),
  '5': Activity(
    uid: '5',
    createdById: '14',
    title: 'Flyvning hos Modern Activity Center',
    location: 'Modern Activity Center',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description:
        'Vi skal fly i vindtunnel. Lang beskrivelse  Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 14,
  ),
  '6': Activity(
    uid: '6',
    createdById: '15',
    title: 'Fadag',
    location: 'Ukjent',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description: 'Vi skal ha kurs i flutter.',
    category: ACTIVITY_CATEGORY.SOCIAL,
    numberOfSignUps: 18,
  ),
  '7': Activity(
    uid: '7',
    createdById: '5',
    title: 'Spille padel',
    location: 'Nordic padel',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 5,
    description: 'Bli med å spille',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 3,
  ),
  '8': Activity(
    uid: '8',
    createdById: '14',
    title: 'Flyvning hos Modern Activity Center',
    location: 'Modern Activity Center',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description:
        'Vi skal fly i vindtunnel. Lang beskrivelse  Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse Lang beskrivelse',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 14,
  ),
  '9': Activity(
    uid: '9',
    createdById: '15',
    title: 'Fadag',
    location: 'Ukjent',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 18,
    description: 'Vi skal ha kurs i flutter.',
    category: ACTIVITY_CATEGORY.SOCIAL,
    numberOfSignUps: 18,
  ),
  '10': Activity(
    uid: '10',
    createdById: '5',
    title: 'Spille padel',
    location: 'Nordic padel',
    time: DateTime.now(),
    answerBy: DateTime.now(),
    numberOfSlots: 5,
    description: 'Bli med å spille',
    category: ACTIVITY_CATEGORY.SPORT,
    numberOfSignUps: 3,
  )
};
