import 'package:progit_activity_booker/models/sign_up.dart';

Map<String, SignUp> SIGN_UPS = {
  '1': SignUp(
    waitingList: 0,
    uid: '1',
    timestamp: 1,
    activityId: '1',
    userId: '1',
  ),
  '2': SignUp(
    waitingList: 0,
    uid: '2',
    timestamp: 1,
    activityId: '1',
    userId: '2',
  ),
  '3': SignUp(
    waitingList: 0,
    uid: '3',
    timestamp: 1,
    activityId: '1',
    userId: '3',
  ),
  '4': SignUp(
    waitingList: 0,
    uid: '4',
    timestamp: 1,
    activityId: '1',
    userId: '4',
  ),
  '5': SignUp(
    waitingList: 0,
    uid: '5',
    timestamp: 1,
    activityId: '1',
    userId: '5',
  ),
  '6': SignUp(
    waitingList: 0,
    uid: '6',
    timestamp: 1,
    activityId: '1',
    userId: '6',
  ),
  '7': SignUp(
    waitingList: 0,
    uid: '7',
    timestamp: 1,
    activityId: '1',
    userId: '7',
  ),
  '8': SignUp(
    waitingList: 0,
    uid: '8',
    timestamp: 1,
    activityId: '1',
    userId: '8',
  ),
  '9': SignUp(
    waitingList: 0,
    uid: '9',
    timestamp: 1,
    activityId: '1',
    userId: '9',
  ),
};

Map<String, SignUp> WAITING_LIST = {
  '10': SignUp(
    waitingList: 1,
    uid: '10',
    timestamp: 1,
    activityId: '1',
    userId: '10',
  ),
  '11': SignUp(
    waitingList: 1,
    uid: '11',
    timestamp: 1,
    activityId: '1',
    userId: '11',
  ),
  '12': SignUp(
    waitingList: 1,
    uid: '12',
    timestamp: 1,
    activityId: '1',
    userId: '12',
  ),
  '13': SignUp(
    waitingList: 1,
    uid: '13',
    timestamp: 1,
    activityId: '1',
    userId: '13',
  ),
  '14': SignUp(
    waitingList: 1,
    uid: '14',
    timestamp: 1,
    activityId: '1',
    userId: '14',
  ),
  '15': SignUp(
    waitingList: 1,
    uid: '15',
    timestamp: 1,
    activityId: '1',
    userId: '15',
  ),
  '16': SignUp(
    waitingList: 1,
    uid: '16',
    timestamp: 1,
    activityId: '1',
    userId: '16',
  ),
  '17': SignUp(
    waitingList: 1,
    uid: '17',
    timestamp: 1,
    activityId: '1',
    userId: '17',
  ),
  '18': SignUp(
    waitingList: 1,
    uid: '18',
    timestamp: 1,
    activityId: '1',
    userId: '18',
  ),
};
