// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvZ48Pz0t9NuYWGZYHw7hcB2db4cpeKY',
    appId: '1:739155390784:web:e569f8b9cc6a682b514aa5',
    messagingSenderId: '739155390784',
    projectId: 'progit-social',
    authDomain: 'progit-social.firebaseapp.com',
    storageBucket: 'progit-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARaPnRcJs89LRray832HA9rRV_kTQlpoA',
    appId: '1:739155390784:android:3798eae5e8b43696514aa5',
    messagingSenderId: '739155390784',
    projectId: 'progit-social',
    storageBucket: 'progit-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qmxD4zuus_D7aOaeYLpS-0Fjyb1afTc',
    appId: '1:739155390784:ios:7978a1f0a929ab56514aa5',
    messagingSenderId: '739155390784',
    projectId: 'progit-social',
    storageBucket: 'progit-social.appspot.com',
    iosClientId: '739155390784-olkfql9f6l2kf5tvmq7l2goskri7h9kt.apps.googleusercontent.com',
    iosBundleId: 'no.progit.progitActivityBooker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qmxD4zuus_D7aOaeYLpS-0Fjyb1afTc',
    appId: '1:739155390784:ios:7978a1f0a929ab56514aa5',
    messagingSenderId: '739155390784',
    projectId: 'progit-social',
    storageBucket: 'progit-social.appspot.com',
    iosClientId: '739155390784-olkfql9f6l2kf5tvmq7l2goskri7h9kt.apps.googleusercontent.com',
    iosBundleId: 'no.progit.progitActivityBooker',
  );
}
